=== coderbyheart/hsrm-mi-wtf/apidocs/schnittstellen.xsd
<?xml version="1.0" encoding="UTF-8"?>
	<!--

		Dieses Dokument dient zur Validierung der
		Schnittstellen-Dokumentations-XML-Datei. @author Markus Tacker
		@version $Id: schnittstellen.xsd 469 2011-07-19 14:45:55Z  $
	-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="leuchttischapi">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="types">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="simpletype" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Definiert einfache Typen wie Skalare,
										Zeichenketten, Chars und Booleans</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="description" type="description" />
										<xs:element name="example" />
										<xs:element name="todo" type="todo" minOccurs="0" />
									</xs:sequence>
									<xs:attribute name="name" type="xs:ID" use="required">
										<xs:annotation>
											<xs:documentation>Name des Types</xs:documentation>
										</xs:annotation>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="enum" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Definiert Enums</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="description" type="description" />
										<xs:element name="example" />
										<xs:element name="items" maxOccurs="unbounded">
											<xs:annotation>
												<xs:documentation>Definiert die Werte eines Enums
												</xs:documentation>
											</xs:annotation>
											<xs:complexType>
												<xs:sequence>
													<xs:element name="item" maxOccurs="unbounded">
														<xs:annotation>
															<xs:documentation>Definiert einen Wert eines Enums
															</xs:documentation>
														</xs:annotation>
														<xs:complexType>
															<xs:sequence>
																<xs:element name="description" type="description" />
															</xs:sequence>
															<xs:attribute name="value" type="xs:string"
																use="required">
																<xs:annotation>
																	<xs:documentation>Der Wert des Enums, wird beim
																		Übertragen verwendet</xs:documentation>
																</xs:annotation>
															</xs:attribute>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="todo" type="todo" minOccurs="0" />
									</xs:sequence>
									<xs:attribute name="name" type="xs:ID" use="required">
										<xs:annotation>
											<xs:documentation>Name des Enums</xs:documentation>
										</xs:annotation>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="complextype" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Definiert komplexe Typen wie Objekte,
										Dictionaries</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="description" type="description" />
										<xs:element name="todo" type="todo" minOccurs="0" />
										<xs:element name="property" type="property"
											maxOccurs="unbounded" />
									</xs:sequence>
									<xs:attribute name="name" type="xs:ID" use="required">
										<xs:annotation>
											<xs:documentation>Name des Types</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="type" use="required">
										<xs:annotation>
											<xs:documentation>Gibt an, um was für eine Art es sich
												handelt.</xs:documentation>
										</xs:annotation>
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:pattern value="Object|Dictionary" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="actions">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="group" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Gruppiert Methoden in Namespaces
									</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="description" type="description" />
										<xs:element name="todo" type="todo" minOccurs="0" />
										<xs:element name="action" maxOccurs="unbounded">
											<xs:complexType>
												<xs:annotation>
													<xs:documentation>Beschreibt eine Methode
													</xs:documentation>
												</xs:annotation>
												<xs:sequence>
													<xs:element name="description" type="description" />
													<xs:element name="todo" type="todo" minOccurs="0" />
													<xs:element name="request">
														<xs:complexType>
															<xs:annotation>
																<xs:documentation>Die akzeptierten Parameter der
																	Methode. Darf leer sein, wenn keine Parameter benötigt
																	werden.</xs:documentation>
															</xs:annotation>
															<xs:sequence>
																<xs:element name="property" type="property"
																	minOccurs="0" maxOccurs="unbounded" />
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="response">
														<xs:complexType>
															<xs:annotation>
																<xs:documentation>Die Elemente der Antwort
																</xs:documentation>
															</xs:annotation>
															<xs:choice>
																<xs:element name="property" type="property"
																	maxOccurs="unbounded">
																	<xs:annotation>
																		<xs:documentation>Listet die Elemente der Antwort als
																			einfache Properties auf.</xs:documentation>
																	</xs:annotation>
																</xs:element>
															</xs:choice>
														</xs:complexType>
													</xs:element>
													<xs:element name="notification" minOccurs="0">
														<xs:complexType>
															<xs:annotation>
																<xs:documentation>Notifications werden versendet, wenn
																	die Aktion durch einen dritten ausgelöst wird.
																</xs:documentation>
															</xs:annotation>
															<xs:choice>
																<xs:element name="property" type="property"
																	maxOccurs="unbounded">
																	<xs:annotation>
																		<xs:documentation>Listet die Elemente der Notification
																			als einfache Properties auf.</xs:documentation>
																	</xs:annotation>
																</xs:element>
															</xs:choice>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="name" type="xs:token" use="required">
													<xs:annotation>
														<xs:documentation>Name der Methode</xs:documentation>
													</xs:annotation>
												</xs:attribute>
												<xs:attribute name="inServer" type="xs:boolean">
													<xs:annotation>
														<xs:documentation>Gibt an, ob die Methode im Server
															implementiert ist</xs:documentation>
													</xs:annotation>
												</xs:attribute>
												<xs:attribute name="inClient" type="xs:boolean">
													<xs:annotation>
														<xs:documentation>Gibt an, ob die Methode im Client
															implementiert ist</xs:documentation>
													</xs:annotation>
												</xs:attribute>
												<xs:attribute name="messageType" type="xs:Name">
													<xs:annotation>
														<xs:documentation>Definiert den Namen mit dem diese
															Schnittstelle als Nachricht identifiziert wird.
														</xs:documentation>
													</xs:annotation>
												</xs:attribute>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name" type="xs:token" use="required">
										<xs:annotation>
											<xs:documentation>Name des Namespaces</xs:documentation>
										</xs:annotation>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="nonEmptyString">
		<xs:annotation>
			<xs:documentation>Ein nicht leerer-Text.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:minLength value="1" />
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="description">
		<xs:annotation>
			<xs:documentation>Enthält eine Beschreibung des Elements
			</xs:documentation>
		</xs:annotation>
		<xs:simpleContent>
			<xs:extension base="nonEmptyString" />
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="todo">
		<xs:annotation>
			<xs:documentation>Enthält die Beschreibung eines offenen Punktes
				(todo) für dieses Element.</xs:documentation>
		</xs:annotation>
		<xs:simpleContent>
			<xs:extension base="nonEmptyString" />
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="property">
		<xs:annotation>
			<xs:documentation>Definiert einen Methoden-Parameter oder einen der
				Werte einer Antwort. Ein Beispiel-Wert wird als Inhalt des Elements
				angegeben.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="example" minOccurs="0"></xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:token" use="required">
			<xs:annotation>
				<xs:documentation>Name der Property</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="type" type="xs:IDREFS" use="required">
			<xs:annotation>
				<xs:documentation>Typ aus der Liste der Typen</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="description" type="nonEmptyString"
			use="required">
			<xs:annotation>
				<xs:documentation>Beschreibung der Property</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="multiple" type="xs:boolean" use="optional">
			<xs:annotation>
				<xs:documentation>Gibt an, ob es sich um eine Liste von Objekten
					dieses Types handelt.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="optional" type="xs:boolean" use="optional">
			<xs:annotation>
				<xs:documentation>Gibt an, ob die Property entfallen kann.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== coderbyheart/hsrm-mi-wtf/apidocs/schnittstellen.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

		Dieses Dokument beschreibt die externe API, die vom Server zur
		Verfügung gestellt wird. Es dient dazu, eine menschen-lesbare
		API-Dokumentation in Form von Wiki-Seite und PDF- Dateien zu erzeugen
		(todo) und automatisierte Tests aus zu führen.

		@author Markus Tacker
		@author Simon Franzen
		@version $Id: schnittstellen.xml 469 2011-07-19 14:45:55Z  $

		TODO: Search-Filter, Search-Filter-List genau definieren
		TODO: User Profile weiter ausbauen
	-->
<leuchttischapi xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schnittstellen.xsd">
  <!--
		Hier werden die im Dokument verwendeten Parameter-Typen definiert.
	-->
  <types>
    <!-- Einfache Typen sind Skalare, Zeichenketten, Chars und Booleans -->
    <simpletype name="String">
      <description>Repräsentiert ein String</description>
      <example>Lorem ipsum</example>
    </simpletype>
    <simpletype name="Integer">
      <description>Repräsentiert ein Integer</description>
      <example>17</example>
    </simpletype>
    <simpletype name="Boolean">
      <description>Repräsentiert ein Boolean</description>
      <example>True</example>
    </simpletype>
    <simpletype name="Float">
      <description>Repräsentiert ein Float</description>
      <example>17.0</example>
    </simpletype>
    <simpletype name="binary">
      <description>Repräsentiert binare Daten, z.B. Bilddaten eines Fotos</description>
      <example>(binary)</example>
    </simpletype>
    <simpletype name="DateTime">
      <description>Repräsentiert ein Datum mit Uhrzeit. Das Format ist YYYY-MM-DDTHH:MM:SS+ZZZZ</description>
      <example>2011-03-28T17:58:23+0001</example>
    </simpletype>
    <enum name="Rating">
      <description>Repräsentiert die Bewertung eines Bildes</description>
      <example>1</example>
      <items>
        <item value="-">
          <description>abgelehnt</description>
        </item>
        <item value="o">
          <description>neutral</description>
        </item>
        <item value="+">
          <description>markiert</description>
        </item>
      </items>
    </enum>
    <enum name="Sex">
      <description>Repräsentiert das Geschlecht einer Person</description>
      <example>M</example>
      <items>
        <item value="M">
          <description>männlich</description>
        </item>
        <item value="F">
          <description>weiblich</description>
        </item>
      </items>
    </enum>
    <enum name="Role">
      <description>Repräsentiert die Rolle einer Person</description>
      <example>Agency</example>
      <items>
        <item value="Agency">
          <description>Agentur</description>
        </item>
        <item value="Customer">
          <description>Kunde</description>
        </item>
        <item value="Photographer">
          <description>Fotograf</description>
        </item>
      </items>
    </enum>
    <enum name="LightboxState">
      <description>Status einer Lightbox</description>
      <example>shared</example>
      <items>
        <item value="private">
          <description>Die Lightbox ist für niemanden zugänglich</description>
        </item>
        <item value="shared">
          <description>Die Lightbox wird mit anderen geteilt</description>
        </item>
        <item value="closed">
          <description>Die Lightbox ist geschlossen.</description>
        </item>
      </items>
    </enum>
    <complextype name="ErrorMessage" type="Object">
      <description>Repräsentiert eine Message mit einer Fehlermeldung</description>
      <property name="id" type="Integer" description="Die ID der Fehlermeldung"/>
      <property name="string" type="String" description="Fehlermeldung">
        <example>Es trat ein Fehler bei der Bildübertragen auf.</example>
      </property>
      <property name="data" type="String" description="Beliebige zusätzliche Daten für die Fehlermeldung">
        <example>Disk quota exceeded</example>
      </property>
    </complextype>
    <complextype name="SuccessMessage" type="Object">
      <description>Repräsentiert eine Message die einen Erfolg wiedergibt</description>
      <property name="id" type="Integer" description="Die ID der Erfolgsmeldung"/>
    </complextype>
    <complextype name="Response" type="Object">
      <description>Repräsentiert eine Antwort</description>
      <property name="iserror" type="Boolean" description="Gibt an, ob es sich um einen Fehler handelt">
        <example>False</example>
      </property>
      <property name="error" type="ErrorMessage" description="Beschreibt den aufgetretenen Fehler, wenn einer aufgetreten ist. Ansonsten ist das Attribut null."/>
      <property name="result" type="SuccessMessage" description="Enthält das Ergebnis der Anfrage"/>
    </complextype>
    <complextype name="Tag" type="Object">
      <description>Repräsentiert ein Tag</description>
      <property name="id" type="Integer" description="Die ID des Tags">
        <example>23344</example>
      </property>
      <property name="userID" type="Integer" description="userID des Besitzers">
        <example>234544</example>
      </property>
      <property name="photoID" type="Integer" description="photoID des zugehörigen Photos">
        <example>234544</example>
      </property>
      <property name="name" type="String" description="Der Tag-String">
        <example>Garten</example>
      </property>
      <property name="role" type="Role" description="Die Rollenzugehörigkeit des Tags">
			</property>
      <property name="isNew" type="Boolean" description="Beschreibt, ob der Tag gerade neu hinzugefügt wurde.">
        <example>234544</example>
      </property>
      <property name="isDeleted" type="Boolean" description="Beschreibt, ob der Tag gerade gelöscht wurde.">
        <example>234544</example>
      </property>
    </complextype>
    <complextype name="Category" type="Object">
      <description>Repräsentiert eine Kategorie</description>
      <property name="id" type="Integer" description="ID der Kategorie">
        <example>55443</example>
      </property>
      <property name="titel" type="String" description="Name der Kategorie">
        <example>Berglandschaft</example>
      </property>
      <property name="parentID" type="Integer" description="Die übergeordnete Kategorie">
        <example>Landschaft</example>
      </property>
    </complextype>
    <complextype name="Lightbox" type="Object">
      <description>Repräsentiert eine Lightbox</description>
      <property name="id" type="Integer" description="ID der Lightbox">
        <example>28388</example>
      </property>
      <property name="name" type="String" description="Name der Lightbox">
        <example>Projekt2011</example>
      </property>
      <property name="description" type="String" description="Beschreibung der Lightbox">
        <example>Das ist die Beschreibung der Lightbox.</example>
      </property>
      <property name="state" type="LightboxState" description="Aktueller Zustand der Lightbox"/>
      <property name="created" type="DateTime" description="Das Erstellungsdatum"/>
      <property name="modified" type="DateTime" description="Das Datum der letzten Änderung"/>
    </complextype>
    <complextype name="PhotoData" type="Object">
      <description>Repräsentiert die Daten eines Fotos</description>
      <todo>FIXME: exif_Timestamp sollte vom Typ DateTime sein. Siehe #419.</todo>
      <property name="id" type="Integer" description="Id des Fotos">
        <example>23334</example>
      </property>
      <property name="deleteFlag" type="Boolean" description="Gibt an, ob das Foto vom Fotografen gelöscht wurde"/>
      <property name="soldFlag" type="Boolean" description="Gibt an, ob das Foto mindestens einmal verkauft wurde."/>
      <property name="name" type="String" description="Name des Fotos">
        <example>Foto001_super</example>
      </property>
      <property name="description" type="String" description="Beschreibung des Fotos">
        <example>23334</example>
      </property>
      <property name="height" type="Integer" description="Höhe des Fotos">
        <example>500</example>
      </property>
      <property name="width" type="Integer" description="Breite des Fotos">
        <example>300</example>
      </property>
      <property name="price" type="Float" description="Preis des Fotos">
        <example>4.90</example>
      </property>
      <property name="exif_Timestamp" type="String" description="exif_Timestamp">
        <example>2011-12-31 17:13:05</example>
      </property>
      <property name="exif_Orientation" type="String" description="exif_Orientation">
        <example>??</example>
      </property>
      <property name="exif_Location" type="String" description="exif_Location">
        <example>??</example>
      </property>
      <property name="category" type="Category" description="Kategorie des Fotos"/>
      <property name="tags" type="Tag" multiple="true" description="Tags des Fotos"/>
      <property name="upload_Timestamp" type="String" description="Das Hochladedatum"/>
      <property name="modified" type="DateTime" description="Das Datum der letzten Änderung"/>
    </complextype>
    <complextype name="AgencyPhotoData" type="Object">
      <description>Repräsentiert Informationen eines agenturspezifischen Fotos</description>
      <property name="id" type="Integer" description="Id des Fotos">
        <example>23334</example>
      </property>
      <property name="name" type="String" description="Agenturspezifische Titel des Bildes">
        <example>Neue Abendsonne</example>
      </property>
      <property name="rate" type="Float" description="Gebühr der Agentur">
        <example>17.0</example>
      </property>
    </complextype>
    <complextype name="LightboxPhotoData" type="Object">
      <description>Repräsentiert die Ligtboxspezifischen Attribute eines Photos</description>
